### ISSUE TITLE
The Search Feature needs a reset method to reset the page

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/NutritionApiV3#1]
When a user leaves the search feature and navigates back the page needs to reset back to normal.

Tasks
1. Clear the list and display the Logo
2. Clear the Search text field 

Controller: _SearchListFrameController.java_

**Comment by KyletheWolff** [comment]
@BrandonVanderMey  any feedback?

**Comment by BrandonVanderMey** [comment]
It's a go.

**Comment by KyletheWolff** [comment]
#34
