### ISSUE TITLE
Create the Fit Tracker View

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/NutritionApiV3#16]
Build the Fit Tracker view with the controller hooked up. Nothing needs to work besides the view to be displaying. 

Use the link to see the design: 
blob:https%3A//mail.google.com/f97f7537-6b52-4b94-a21e-f9c81e63c045

AC:
1. At the bottom of the view we need a static row that has SUN - SAT
2. Above the static days of week row is the +Add Exercise button 
3. There will be nothing displaying where the workouts will be - Different Story
4. At the top we need blank field for a name of the workout that day

FOLLOW THE DESIGN.

**Comment by KyletheWolff** [comment]
@BrandonVanderMey is this good to go to start working?

**Comment by BrandonVanderMey** [comment]
It is good to start working.  However, if there is going to be some animation in the fitTracker layer, keep in mind of which panels are going to be animated so that later (very soon) when my animation library is perfected, it will be simple to implement.

P.S. The link you have provided is broken.

**Comment by KyletheWolff** [comment]
Closed
