### ISSUE TITLE
Create Custom Cell for the Fitracker View

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/NutritionApiV3#21]
blob:https%3A//mail.google.com/f97f7537-6b52-4b94-a21e-f9c81e63c045

The image above displays the entire fitracker view the only thing we are concerned about is the stuff beneath the title of the workout beginning at SitUps. 
1. Need the spot for the name 
2. Then just weights reps and sets like the design

**Comment by KyletheWolff** [comment]
@BrandonVanderMey  Please comment when ready

**Comment by BrandonVanderMey** [comment]
Good to go.
