### ISSUE TITLE
Global CSS

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/NutritionApiV3#30]
(Unfinished) 

We have a few places for CSS code is duplicated. We could however dig into the css code see where we have things are a like and update accordingly. 

We also need to change our color palette which will help us create a Global CSS file. 

Colors: 

Use http://www.materialui.co/colors

Background: #8BC34A or White depending on what is being worked on 
Action: #76FF03
Action if white text: #B6B6B6
Primary Text: #212121
Text (White) : #DCEDC8
Icons: #212121 (If we can change the color) 

If you have any questions let me know

**Comment by BrandonVanderMey** [comment]
We should implement this.  Marked Approved.

**Comment by KyletheWolff** [comment]
Do you want me to work on this?

**Comment by BrandonVanderMey** [comment]
Since you have used CSS the most in this program, yes.  Because I wouldn't know what to change

**Comment by KyletheWolff** [comment]
We need to get together so we can go through it

**Comment by KyletheWolff** [comment]
There will be no set standard for items that are customized for a specifc view. The items use quite a bit will be a set standard.
