### ISSUE TITLE
Add a way to delete exercises

### ISSUE THREAD

**Issue by BrandonVanderMey** [TheLearningCurve/NutritionApiV3#39]
1. Click on Fit Tracker.
2. Click "+Exercise" a bunch of times.  There's no way of removing extra exercises.

Fix: 
We need to put either a - Delete Exercise (button) 
Or put a button directly with the cell 

Either way will work. It might be easier with a delete exercise button and a button to select from the list

**Comment by KyletheWolff** [comment]
Approved to work on.
