### ISSUE TITLE
Add custom animation library.

### ISSUE THREAD

**Issue by BrandonVanderMey** [TheLearningCurve/NutritionApiV3#4]
What I want to do is create a library (or a package) that lets us animate panels in a very easy way.

Estimated Time = 01/11 Or 01/12

**Comment by KyletheWolff** [comment]
Estimated Time?

**Comment by BrandonVanderMey** [comment]
ETA: Monday or Tuesday.  This is the first thing I am going to be working on.

**Comment by BrandonVanderMey** [comment]
Since some issues have arose with this, I will have to re-try with a different approach.
