### ISSUE TITLE
Convert the custom list on the search feature using the JavaFX listView

### ISSUE THREAD

**Issue by KyletheWolff** [TheLearningCurve/NutritionApiV3#6]
(Unfinished need a story for the custom cells to go with this) 

Currently I built a custom listView to display the nutrition items. The issue is we are creating new objects every time. The correct way to handle a list is virtualization which basically means; the only objects that get created are the objects displaying on page. When the user scrolls the cell at the top will become the cell at the bottom this is called recycling. 
![recycler](https://cloud.githubusercontent.com/assets/10425034/12218283/9c859daa-b6e8-11e5-8e3f-3e5bd86acaa0.jpg)

**Comment by BrandonVanderMey** [comment]
This is a great idea and I like it.  Let's go forward with this enhancement!

**Comment by KyletheWolff** [comment]
Working on this at the moment. Hopefully will be done this weekend depending on home work

**Comment by KyletheWolff** [comment]
Closed
